var kata_bijak=new Array()
kata_bijak[0]="Seseorang yang luar biasa itu sederhana dalam ucapannya, Tetapi hebat dalam tindakanya  -- AGM Pulsa dan PPOB --";
kata_bijak[1]="Suatu hal yang patut menjadi kebanggaan adalah ketika seseorang memutuskan untuk menjadi dirinya sendiri.  -- AGM Pulsa dan PPOB --";
kata_bijak[2]="Agar masa depanmu lebih baik maka berusahalah mulai dari sekarang.  -- AGM Pulsa dan PPOB --";
kata_bijak[3]="Masa depan bukanlah tujuan utama, melainkan perbaikan melalui tindakan yang benar – benar nyata. -- AGM Pulsa dan PPOB --";
kata_bijak[4]="Kamu harus mengetahui tujuan utama masa depanmu, agar kamu tahu sepenuhnya tujuan hidupmu. -- AGM Pulsa dan PPOB --";
kata_bijak[5]="Merupakan suatu hal yang sangat sukar ketika semua yang awalnya baik tiba - tiba berubah menjadi buruk. Dan yang lebih sukar dari itu adalah memilih sebuah pilihan antara melepaskan atau tetap bertahan. -- AGM Pulsa dan PPOB --";
kata_bijak[6]="Ketika kamu bermimpi, jagan pernah takut untuk bermimpi setinggi – tingginya, karena ketka Tuhan berkehendak engkau bermimpi setinggi – tingginya, berarti Dia pun berkehendak bahwa kamu bisa mewujudkannya. -- AGM Pulsa dan PPOB --";
kata_bijak[7]="Teruslah percaya dan bekerja keraslah -- AGM Pulsa dan PPOB --";
kata_bijak[8]="Jika bisa menjadi sukses sewaktu muda, kenapa harus menunggu usia tua? -- AGM Pulsa dan PPOB --";
kata_bijak[9]="Kurang pandai mungkin bisa di perbaiki, tapi kejujuran tidak akan pernah mudah untuk di tanamkan -- AGM Pulsa dan PPOB --";
kata_bijak[10]="Jangan hanya memandang dari salah satu sisi, agar pandanganmu tidak tersempitkan -- AGM Pulsa dan PPOB --";
kata_bijak[11]="Jauhilah orang yang banyak berfikir negative karena dari sana akan muncul masalah dari sebuah solusi yang ada -- AGM Pulsa dan PPOB --";
kata_bijak[12]="Dengan bekerja keras engkau akan mengalahkan orang – orang yang berbakat -- AGM Pulsa dan PPOB --";
kata_bijak[13]="Ketika kamu memiliki keyakinan untuk mampu melakukan maka kamu akan bisa mewujudkan segala mimpimu -- AGM Pulsa dan PPOB --";
kata_bijak[14]="Orang yang bertindak tanpa berpikir adalah orang yang gagal -- AGM Pulsa dan PPOB --";
kata_bijak[15]="Gagal adalah masalah kecil namun putus asa adalah masalah yang besar -- AGM Pulsa dan PPOB --";
kata_bijak[16]="Sebuah langkah kecil adalah sebuah awal jalan yang panjang -- AGM Pulsa dan PPOB --";
kata_bijak[17]="Tekuni salah satu bidang maka Anda akan menjadi orang hebat yang berhasil -- AGM Pulsa dan PPOB --";
kata_bijak[18]="harapan dan keinginan ini semestinya sejalan, yah sejalan dengan seberapa besar usaha ia dalam mewujudkannya -- AGM Pulsa dan PPOB --";
kata_bijak[19]="Seorang juara pasti akan percaya pada dirinya sendiri, walaupun tidak ada orang yang mau mempercayainya lagi -- AGM Pulsa dan PPOB --";
kata_bijak[20]="Ketakutan harus dikerdilkan, karena ketakutan adalah musuh besar impian yang akan diwujudkan -- AGM Pulsa dan PPOB --";
kata_bijak[21]="Kerja keras orang tua itu karena ingin anak – anaknya menjadi pribadi yang bukan hanya biasa tapi luar biasa -- AGM Pulsa dan PPOB --";
kata_bijak[22]="Saat orang lain disekitarmu berkata bahwa dirimu telah berubah, sebenarnya hanyalah engkau mulai berhenti untuk tidak melakukan hal – hal yang sperti biasanya mereka ingin Anda melakukannya. -- AGM Pulsa dan PPOB --";
kata_bijak[23]="Agar langkah sukses Ada 10 kali lebih cepat, maka Anda perlu mempunyai keberanian untuk mengambil keputusan. -- AGM Pulsa dan PPOB --";
kata_bijak[24]="Kesuksesan akan sangat jauh, apabila Anda bayak melakukan hal – hal yang sia – sia. -- AGM Pulsa dan PPOB --";
kata_bijak[25]="Sebuah keputusan yang paling baik ialah dengan berpedoman pengalaman hidup. Dan pengalaman hidup diperoleh dari keputusan yang pernah salah -- AGM Pulsa dan PPOB --";
kata_bijak[26]="Setiap hari sangatlah berharga, janganlah menunggu waktu yang tepat untuk mulai melangkah. -- AGM Pulsa dan PPOB --";
kata_bijak[27]="Sebuah keberuntunga akn datang ketika Anda dapat mengambil peluang dan kesempatan dengan persiapan yang matang -- AGM Pulsa dan PPOB --";
kata_bijak[28]="Sikap Anda saat ini adalah bentuk dari pengalaman hidup Anda -- AGM Pulsa dan PPOB --";
kata_bijak[29]="Waktu sangatlah berharga, janganlah pernah menyia – nyiakannya -- AGM Pulsa dan PPOB --";
kata_bijak[30]="Waktu itu ibarat pedang yang bila digunakan dengan baik akan membwamu pada sebuah keberuntungan dan sebaliknya jika engkau lalai akan membunuhmu. -- AGM Pulsa dan PPOB --";
kata_bijak[31]="Teruslah optimis dan berpikir positif dalam hidupmu. -- AGM Pulsa dan PPOB --";
kata_bijak[32]="Ketika ada sebuah keinginan yang muncul untuk memulai suatu hal yang sudah di targetkan, maka harus muncul sebuah keberanian untuk menyelesaikannya. -- AGM Pulsa dan PPOB --";
kata_bijak[33]="Jangan menunda untuk lekas berusaha demi keindahan masa depanmu -- AGM Pulsa dan PPOB --";

var acak=Math.floor(33*Math.random());
document.write("<i>");
document.write(kata_bijak[acak]);
document.write("</i>");