document.writeln(" <div class=\"py-5 text-center\"> "); 
document.writeln("       <div class=\"container\"> "); 
document.writeln("         <div class=\"row\"> "); 
document.writeln("           <div class=\"col-md-12\"> "); 
document.writeln("             <div class=\"row\"> "); 
document.writeln("               <div class=\"col-md-6\"> "); 
document.writeln("                 <div class=\"alert alert-secondary\" role=\"alert\"> "); 
document.writeln("                   <h4 class=\"alert-heading\"> "); 
document.writeln("                     <b>FORMAT TRANSAKSI</b> "); 
document.writeln("                     <br> "); 
document.writeln("                     <br> </h4> "); 
document.writeln("                   <p class=\"mb-0 text-left\"> "); 
document.writeln("                     <b>Semua Transaksi dikirim ke Jabber / Telegram / Gtalk / Hangout / SMS Center / Nimbuzz Center. Adapun Format Transaksi yang disediakan adalah sebagai berikut :&nbsp;&nbsp;&nbsp;<br> "); 
document.writeln("                       <br>Format bebas bisa menggunakan karakter :&nbsp;</b><br><b>[ . ] / [ , ] / [ # ] / [ * ] / [ sepasi ] / [ Campur ]</b><br><b>Contoh&nbsp;</b><br>Titik : 10.081234567893.1234<br>Koma :&nbsp;10,081234567893,1234<br>Pagar : 10#081234567893#1234<br>Bintang :10*081234567893*1234<br>Sepasi : 10 081234567893 1234<br>Campur : 10#08123456783*1234<br><br></p> "); 
document.writeln("                   <ul class=\"text-left\"> "); 
document.writeln("                     <li class=\"text-left\"> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Daftar Menjadi MASTER</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : &lt;REG&gt;#&lt;AGM&gt;#&lt;NAMA/KONTER&gt;#&lt;KOTA&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : REG#AGM#JOKO#JAKARTA</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Transaksi Isi Pulsa</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : &lt;koode&gt;.&lt;no hp&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : SS10.081234567890.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Transaksi Isi Pulsa Tanpa Kode</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : &lt;nominal&gt;.&lt;no hp&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : 10.081234567890.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Transaksi Token PLN TANPA NO TUJUAN</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : &lt;nominal&gt;.&lt;no token&gt;.&lt;no hp tujuan&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : PLN20.34012312345.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Transaksi Token PLN</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : &lt;nominal&gt;.&lt;no token&gt;.&lt;no hp tujuan&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : PLN20.34012312345.081234567890.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Transaksi Isi Pulsa Ke No Hp dan Nominal Yang Sama Ke 2,3,4 dst</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : &lt;koode&gt;.&lt;2,3,4,dst&gt;&lt;no hp&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : SS10.2.081234567890.1234 <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"></span> "); 
document.writeln("                       </span> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\">&nbsp;</span> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\">Contoh Tanpa kode: 10.3.081234567890.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Cek Saldo</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : S.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : S.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Cek&nbsp;Saldo Downline</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : Saldo.&lt;id_agen&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : Saldo.AB007.&lt;pin&gt;</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Cek Harga</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : H.KodeProduk.Pin</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : H.S.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Ganti Pin</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : GPIN.&lt;pinbaru&gt;.&lt;pinlama&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : PIN.SaMurai7094.1234</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Catatan : PIN Bebas boleh angkan / huruf disarankan kominasi angkahuruf dan panjang agar aman</span> "); 
document.writeln("                       <br> </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Tambah Hp</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : HP.&lt;nomorhpbaru&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : HP.0877412345.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Daftar Downline</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : D.&lt;nama&gt;.&lt;nohpdownline&gt;.&lt;up&gt;.&lt;alamat&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : D.Kios Cell.0812222122.50.Bandung.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Kirim Saldo</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : KIRIM.&lt;id_member&gt;.&lt;jumlah&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : Kirim.OK001.200000.5555</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Cek Bonus/Rebate</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : BONUS.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : BONUS.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Cek Status Transaksi</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : STATUS.&lt;tujuan&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : STATUS.0812345789.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Komplain</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : INFO.&lt;isipesan&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : INFO.isi 10rb ke 0812222121 blm mask tgl.18 tolong bntu.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Tiket Deposit</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : TIKET.&lt;Jumlah&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : TIKET.500000.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Hapus Tiket</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : HTIKET.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : HTIKET.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Blokir&nbsp;Downline</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : Blokir.&lt;id_agen&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : Blokir.BJ003.&lt;pin&gt;</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Buka Blokir&nbsp;</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format :&nbsp;Buka.&lt;id_agen&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh :&nbsp;Buka.BJ003.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Ubah&nbsp;Up/Mark up Harga</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : UBAH.&lt;id_downline&gt;.&lt;upbaru&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : UBAH.IN002.100.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Ubah&nbsp;Up/Mark up Perkodeproduk</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : SETUP.&lt;id_agen&gt;.&lt;kode&gt;.&lt;up&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : SETUP.TE001.S5.50.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Ubah&nbsp;Up/Mark up Pernominal</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : SETUP.&lt;id_agen&gt;.&lt;nominal&gt;.&lt;up&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : SETUP.TE001.100000.300.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Ubah&nbsp;Up/Mark up Perkodeproduk SemuaAgen&nbsp;</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : SETUP.ALL.&lt;kode&gt;.&lt;up&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : SETUP.ALL.S5.50.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Ubah&nbsp;Up/Mark up Pernominal SemuaAgen</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : SETUP.ALL.&lt;nominal&gt;.&lt;up&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : SETUP.ALL.100000.50.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Cek Tagihan PPOB</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : CEK.PLN/TELKOM/BPJS/HALO/PDAM/SPEEDY.&lt;id_pelanggan&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : CEK.PLN.53531004567699.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Bayar Tagihan PPOB</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : BAYAR.&lt;id_pelanggan&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : BAYAR.535210045676.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Tarik Saldo</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : TARIK.&lt;id_member&gt;.&lt;jumlah&gt;.&lt;sebabtariksaldo&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : TARIK.IK008.50000.Salah Kirim.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Set Hp Utama</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : HPUTAMA.&lt;nomorhpygterdaftar&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : HPUTAMA.0812345454511.&lt;pin&gt;</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Hapus Nomor Paralel</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : HAPUSHP.&lt;nomorparalel&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : HAPUSHP.0877788882222.&lt;pin&gt;</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Cek Semua Nomor</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : SEMUAHP.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : SEMUAHP.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Set Trx Tanpa Pin</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : SETPIN.&lt;0 atau 1&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : SETPIN.1.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Ganti Nama Member</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : Gantinama.&lt;namabaru&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : Gantinama.Abadi&nbsp;Cell.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>Ambil Bonus REBATE</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : AMBIL.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : AMBIL.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>ADD Google Talk</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : GTALK.&lt;id/account&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : GTALK.Joko@gmail.com.1234</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>ADD JABBER</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : JABBER.&lt;id/account&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : JABBER.joko@jabbim.com.&lt;pin&gt;</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>ADD NIMBUZZ</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : NIMBUZZ.&lt;id/account&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : NIMBUZZ.Raisa@nimbuzz.com.&lt;pin&gt;</span> "); 
document.writeln("                     </li> "); 
document.writeln("                     <br> "); 
document.writeln("                     <li> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> "); 
document.writeln("                         <b>ADD TELEGRAMBOT</b> "); 
document.writeln("                       </span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Format : TELEGRAM.&lt;ID telegram&gt;.&lt;pin&gt;</span> "); 
document.writeln("                       <br> "); 
document.writeln("                       <span style=\"font-family: &quot;arial&quot; , &quot;helvetica&quot; , sans-serif;\"> Contoh : TELEGRAM.11251244412.1234</span><br><br>TELEGRAM CENTER KAMI&nbsp; :&nbsp;<br> "); 
document.writeln("                       @ctr1000bot ");
document.writeln("                       <br> "); 
document.writeln("                       @ctr2000bot "); 
document.writeln("                       <br> "); 
document.writeln("                       @ctr3000bot "); 
document.writeln("                       <br> "); 
document.writeln("                       @ctr4000bot "); 
document.writeln("                       <br> ");
document.writeln("                       <br> ");
document.writeln("                     <br> "); 
document.writeln("                   </ul> "); 
document.writeln("                 </div> "); 
document.writeln("               </div> "); 
document.writeln("               <div class=\"col-md-6\"> "); 
document.writeln("                 <div class=\"alert alert-dark\" role=\"alert\"> "); 
document.writeln("                   <h4 class=\"alert-heading\"> "); 
document.writeln("                     <b>CENTER TRANSAKSI</b> "); 
document.writeln("                     <br> "); 
document.writeln("                     <br> </h4> "); 
document.writeln("                   <p class=\"mb-0 text-left text-dark\"> "); 
document.writeln("                     <b>TELEGRAM CHANNEL <br> "); 
document.writeln("                       <a title=\"@agmpulsa\" href=\"https://t.me/agmpulsa\" target=\"_blank\"> "); 
document.writeln("                         <span class=\"fa fa-telegram fa-lg\"></span> "); 
document.writeln("                       </a> @agmpulsa</b>&nbsp; <br><br><b>Transaksi Suport</b><br><b>- TTS</b><br><b>- Jabber</b><br><b>- Gtalk/Hangout</b><br><b>- Telegram</b><br><br><b>TELEGRAM CENTER &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <br> "); 
document.writeln("                       <a title=\"@ctr1000bot\"> "); 
document.writeln("                         <span class=\"fa fa-telegram fa-lg\"></span> "); 
document.writeln("                       </a> @ctr1000bot <br> "); 
document.writeln("                       <a title=\"@ctr2000bot\"> "); 
document.writeln("                         <span class=\"fa fa-telegram fa-lg\"></span> "); 
document.writeln("                       </a> @ctr2000bot <br> "); 
document.writeln("                       <a title=\"@ctr3000bot\"> "); 
document.writeln("                         <span class=\"fa fa-telegram fa-lg\"></span> "); 
document.writeln("                       </a> @ctr3000bot <br> "); 
document.writeln("                       <a title=\"@ctr4000bot\"> "); 
document.writeln("                         <span class=\"fa fa-telegram fa-lg\"></span> "); 
document.writeln("                       </a> @ctr4000bot <br> "); 
document.writeln("                       <br>JABBER&nbsp; / XMPP</b>&nbsp;<br> "); 
document.writeln("                     <b>ctragm@xabber.org <br>ctragm@jabber.at<br>ctragm@xmpp.jp<br>ctragm@jabb.im<br>ctragm@xmpp.is<br>ctragm@kode.im<br>ctragm@jabbim.cz</b> "); 
document.writeln("                     <br> "); 
document.writeln("                     <b>ctr1000@jabbim.com <br>ctr2000@jabbim.com <br>ctr3000@jabb.im <br>ctr4000@jabb.im <br>ctr1000@xmpp.jp <br>ctr2000@xmpp.jp <br>ctr3000@xmpp.jp <br>ctr4000@xmpp.jp <br> "); 
document.writeln("                       <br>GTALK / HANGOUT <br>ctr1000bot@gmail.com <br>ctr2000bot@gmail.com <br>ctr3000bot@gmail.com <br> "); 
document.writeln("                       <br>SMS [ kusus pendaftaran ] <br>0895637936618 <br>089652173202 <br>083890625586 <br> "); 
document.writeln("                       <br> </b> "); 
document.writeln("                   </p> "); 
document.writeln("                   <div class=\"row\"> "); 
document.writeln("                     <div class=\"col-md-8 text-left text-capitalize\"> "); 
document.writeln("                       <p> "); 
document.writeln("                         <b>Download aplikasi pendukung PC / Android</b> "); 
document.writeln("                       </p> "); 
document.writeln("                     </div> "); 
document.writeln("                     <div class=\"col-md-2 p-0\"> "); 
document.writeln("                       <a class=\"btn btn-primary btn-sm btn-block\" href=\"download.html\" target=\"_blank\">Disini</a> "); 
document.writeln("                     </div> "); 
document.writeln("                   </div> "); 
document.writeln("                   <b> </b> "); 
document.writeln("                 </div> "); 
document.writeln("                 <b> "); 
document.writeln("                   <div class=\"alert alert-success\" role=\"alert\"> "); 
document.writeln("                     <h4 class=\"alert-heading\"> "); 
document.writeln("                       <b>DAFTAR BANK</b> "); 
document.writeln("                       <br> "); 
document.writeln("                       <br> </h4> "); 
document.writeln("                     <p class=\"mb-0 text-left\">Setelah Mendaftar menjadi mitra pulsa kami, langkah selanjutnya adalah deposit pulsa / menambah saldo agar dapat digunakan untuk transaksi semua produk terlengkap dari AGM Pulsa dan PPOB. Harap diperhatikan, cara deposit saldo agen pulsa yang kami terapkan saat ini pastikan nominal harus sama dengan yg didapat melalui TIKET DEPOSIT, jika tidak sama dengan tiket deposit dana kami kembalikan dengan proses manual. <br> "); 
document.writeln("                       <br> "); 
document.writeln("                       <br> </p> "); 
document.writeln("                     <img class=\"d-block img-fluid mx-auto rounded p-2\" src=\"upload/bri.jpg\" width=\"134\" height=\"40\"> "); 
document.writeln("                     <p class=\"text-center\"> "); 
document.writeln("                       <b>002801047027504 : a/n Daniel Corsel</b> "); 
document.writeln("                       <br> "); 
document.writeln("                       <br> </p> "); 
document.writeln("                     <img class=\"img-fluid d-block mx-auto p-2\" src=\"upload/bni.jpg\" width=\"134\" height=\"40\"> "); 
document.writeln("                     <p class=\"\"> "); 
document.writeln("                       <b>0673719166 : a/n Daniel Corsel</b> "); 
document.writeln("                       <br> "); 
document.writeln("                       <br> </p> "); 
document.writeln("                     <img class=\"img-fluid d-block mx-auto p-2\" src=\"upload/mandiri.jpg\" width=\"134\" height=\"40\"> "); 
document.writeln("                     <p class=\"\"> "); 
document.writeln("                       <b>1340013484935 : a/n Daniel Corsel</b> "); 
document.writeln("                       <br> "); 
document.writeln("                       <br> </p> "); 
document.writeln("                     <img class=\"img-fluid d-block p-2 mx-auto\" src=\"upload/bca.jpg\" width=\"134\" height=\"40\"> "); 
document.writeln("                     <p class=\"\" contenteditable=\"true\">3030596195 : a/n Daniel Corsel <br> "); 
document.writeln("                       <br> </p> "); 
document.writeln("                   </div> "); 
document.writeln("                 </b> "); 
document.writeln("               </div> "); 
document.writeln("               <b> </b> "); 
document.writeln("             </div> "); 
document.writeln("             <b> </b> "); 
document.writeln("           </div> "); 
document.writeln("           <b> </b> "); 
document.writeln("         </div> "); 
document.writeln("         <b> </b> "); 
document.writeln("       </div> "); 
document.writeln("       <b> </b> "); 
document.writeln("     </div> ");