document.write('<div class=\"py-5 text-center\" >\n');
document.write(' <div class=\"container\">\n');
document.write(' <div class=\"row\">\n');
document.write(' <div class=\"col-md-12\">\n');
document.write(' <div class=\"row\">\n');
document.write(' <div class=\"col-md-6\">\n');
document.write(' <div class=\"alert alert-secondary\" role=\"alert\">\n');
document.write(' <h4 class=\"alert-heading\">\n');
document.write(' <b>FORMAT TRANSAKSI</b>\n');
document.write(' <br>\n');
document.write(' <br> </h4>\n');
document.write(' <p class=\"mb-0 text-left\">\n');
document.write(' <b>Semua Transaksi dikirim ke Jabber / Telegram / Gtalk / Hangout / SMS Center / Nimbuzz Center. Adapun Format Transaksi yang disediakan adalah sebagai berikut : <br>\n');
document.write(' <br>Format bebas bisa menggunakan karakter : </b><br><b>[ . ] / [ , ] / [ # ] / [ * ] / [ sepasi ] / [ Campur ]</b><br><b>Contoh </b><br>Titik : 10.081234567893.1234<br>Koma : 10,081234567893,1234<br>Pagar : 10#081234567893#1234<br>Bintang :10*081234567893*1234<br>Sepasi : 10 081234567893 1234<br>Campur : 10#08123456783*1234<br><br></p>\n');
document.write(' <ul class=\"text-left\">\n');
document.write(' <li class=\"text-left\">\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Daftar Menjadi MASTER</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : <REG>#<AGM>#<NAMA/KONTER>#<KOTA></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : REG#AGM#JOKO#JAKARTA</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Transaksi Isi Pulsa</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : <koode>.<no hp>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : SS10.081234567890.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Transaksi Isi Pulsa Tanpa Kode</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : <nominal>.<no hp>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : 10.081234567890.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Transaksi Token PLN TANPA NO TUJUAN</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : <nominal>.<no token>.<no hp tujuan>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : PLN20.34012312345.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Transaksi Token PLN</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : <nominal>.<no token>.<no hp tujuan>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : PLN20.34012312345.081234567890.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Transaksi Isi Pulsa Ke No Hp dan Nominal Yang Sama Ke 2,3,4 dst</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : <koode>.<2,3,4,dst><no hp>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : SS10.2.081234567890.1234 <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"></span>\n');
document.write(' </span>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> </span>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">Contoh Tanpa kode: 10.3.081234567890.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Cek Saldo</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : S.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : S.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Cek Saldo Downline</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : Saldo.<id_agen>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : Saldo.AB007.<pin></span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Cek Harga</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : H.KodeProduk.Pin</span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : H.S.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Ganti Pin</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : GPIN.<pinbaru>.<pinlama></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : PIN.SaMurai7094.1234</span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Catatan : PIN Bebas boleh angkan / huruf disarankan kominasi angkahuruf dan panjang agar aman</span>\n');
document.write(' <br> </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Tambah Hp</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : HP.<nomorhpbaru>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : HP.0877412345.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Daftar Downline</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : D.<nama>.<nohpdownline>.<up>.<alamat>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : D.Kios Cell.0812222122.50.Bandung.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Kirim Saldo</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : KIRIM.<id_member>.<jumlah>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : Kirim.OK001.200000.5555</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Cek Bonus/Rebate</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : BONUS.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : BONUS.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Cek Status Transaksi</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : STATUS.<tujuan>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : STATUS.0812345789.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Komplain</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : INFO.<isipesan>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : INFO.isi 10rb ke 0812222121 blm mask tgl.18 tolong bntu.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Tiket Deposit</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : TIKET.<Jumlah>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : TIKET.500000.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Hapus Tiket</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : HTIKET.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : HTIKET.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Blokir Downline</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : Blokir.<id_agen>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : Blokir.BJ003.<pin></span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Buka Blokir </b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : Buka.<id_agen>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : Buka.BJ003.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Ubah Up/Mark up Harga</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : UBAH.<id_downline>.<upbaru>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : UBAH.IN002.100.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Ubah Up/Mark up Perkodeproduk</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : SETUP.<id_agen>.<kode>.<up>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : SETUP.TE001.S5.50.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Ubah Up/Mark up Pernominal</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : SETUP.<id_agen>.<nominal>.<up>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : SETUP.TE001.100000.300.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Ubah Up/Mark up Perkodeproduk SemuaAgen </b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : SETUP.ALL.<kode>.<up>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : SETUP.ALL.S5.50.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Ubah Up/Mark up Pernominal SemuaAgen</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : SETUP.ALL.<nominal>.<up>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : SETUP.ALL.100000.50.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Cek Tagihan PPOB</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : CEK.PLN.<id_pelanggan>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : CEK.PLN.53531004567699.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Bayar Tagihan PPOB</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : BAYAR.<id_pelanggan>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : BAYAR.535210045676.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Tarik Saldo</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : TARIK.<id_member>.<jumlah>.<sebabtariksaldo>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : TARIK.IK008.50000.Salah Kirim.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Set Hp Utama</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : HPUTAMA.<nomorhpygterdaftar>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : HPUTAMA.0812345454511.<pin></span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Hapus Nomor Paralel</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : HAPUSHP.<nomorparalel>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : HAPUSHP.0877788882222.<pin></span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Cek Semua Nomor</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : SEMUAHP.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : SEMUAHP.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Set Trx Tanpa Pin</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : SETPIN.<0 atau 1>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : SETPIN.1.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Ganti Nama Member</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : Gantinama.<namabaru>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : Gantinama.Abadi Cell.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>Ambil Bonus REBATE</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : AMBIL.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : AMBIL.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>ADD Google Talk</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : GTALK.<id/account>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : GTALK.Joko@gmail.com.1234</span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>ADD JABBER</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : JABBER.<id/account>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : JABBER.joko@jabbim.com.<pin></span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>ADD NIMBUZZ</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : NIMBUZZ.<id/account>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : NIMBUZZ.Raisa@nimbuzz.com.<pin></span>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' <li>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\">\n');
document.write(' <b>ADD TELEGRAMBOT</b>\n');
document.write(' </span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Format : TELEGRAM.<ID telegram>.<pin></span>\n');
document.write(' <br>\n');
document.write(' <span style=\"font-family: "arial" , "helvetica" , sans-serif;\"> Contoh : TELEGRAM.11251244412.1234</span><br><br>TELEGRAM CENTER KAMI : <br>\n');
document.write(' <a href=\"https://telegram.me/ctr1000bot\" target=\"_blank\">@ctr1000bot</a>\n');
document.write(' <br>\n');
document.write(' <a href=\"https://telegram.me/ctr2000bot\" target=\"_blank\">@ctr2000bot</a>\n');
document.write(' <br>\n');
document.write(' <a href=\"https://telegram.me/ctr3000bot\" target=\"_blank\">@ctr3000bot</a>\n');
document.write(' <br>\n');
document.write(' <a href=\"https://telegram.me/ctr4000bot\" target=\"_blank\">@ctr4000bot</a>\n');
document.write(' <br>\n');
document.write(' </li>\n');
document.write(' <br>\n');
document.write(' </ul>\n');
document.write(' </div>\n');
document.write(' </div>\n');
document.write(' <div class=\"col-md-6\">\n');
document.write(' <div class=\"alert alert-dark\" role=\"alert\">\n');
document.write(' <h4 class=\"alert-heading\">\n');
document.write(' <b>CENTER TRANSAKSI</b>\n');
document.write(' <br>\n');
document.write(' <br> </h4>\n');
document.write(' <p class=\"mb-0 text-left text-dark\">\n');
document.write(' <b>TELEGRAM CHANNEL <br>\n');
document.write(' <a title=\"@agmpulsa\" href=\"https://t.me/agmpulsa\" target=\"_blank\">\n');
document.write(' <span class=\"fa fa-telegram fa-lg\"></span>\n');
document.write(' </a> @agmpulsa</b> <br><br><b>Transaksi Suport</b><br><b>- TTS</b><br><b>- Jabber</b><br><b>- Gtalk/Hangout</b><br><b>- Telegram</b><br><br><b>TELEGRAM CENTER <br>\n');
document.write(' <a title=\"@ctr1000bot\" href=\"https://telegram.me/ctr1000bot\" target=\"_blank\">\n');
document.write(' <span class=\"fa fa-telegram fa-lg\"></span>\n');
document.write(' </a> @ctr1000bot <br>\n');
document.write(' <a title=\"@ctr2000bot\" href=\"https://telegram.me/ctr2000bot\" target=\"_blank\">\n');
document.write(' <span class=\"fa fa-telegram fa-lg\"></span>\n');
document.write(' </a> @ctr2000bot <br>\n');
document.write(' <a title=\"@ctr3000bot\" href=\"https://telegram.me/ctr3000bot\" target=\"_blank\">\n');
document.write(' <span class=\"fa fa-telegram fa-lg\"></span>\n');
document.write(' </a> @ctr3000bot <br>\n');
document.write(' <a title=\"@ctr4000bot\" href=\"https://telegram.me/ctr4000bot\" target=\"_blank\">\n');
document.write(' <span class=\"fa fa-telegram fa-lg\"></span>\n');
document.write(' </a> @ctr4000bot <br>\n');
document.write(' <br>JABBER / XMPP</b> <br>\n');
document.write(' <b>ctragm@xabber.org <br>ctragm@jabber.at<br>ctragm@xmpp.jp<br>ctragm@jabb.im<br>ctragm@xmpp.is<br>ctragm@kode.im<br>ctragm@jabbim.cz</b>\n');
document.write(' <br>\n');
document.write(' <b>ctr1000@jabbim.com <br>ctr2000@jabbim.com <br>ctr3000@jabb.im <br>ctr4000@jabb.im <br>ctr1000@xmpp.jp <br>ctr2000@xmpp.jp <br>ctr3000@xmpp.jp <br>ctr4000@xmpp.jp <br>\n');
document.write(' <br>GTALK / HANGOUT <br>ctr1000bot@gmail.com <br>ctr2000bot@gmail.com <br>ctr3000bot@gmail.com <br>\n');
document.write(' <br>SMS [ kusus pendaftaran ] <br>0895637936618 <br>089652173202 <br>083890625586 <br>\n');
document.write(' <br> </b>\n');
document.write(' </p>\n');
document.write(' <div class=\"row\">\n');
document.write(' <div class=\"col-md-8 text-left text-capitalize\">\n');
document.write(' <p>\n');
document.write(' <b>Download aplikasi pendukung PC / Android</b>\n');
document.write(' </p>\n');
document.write(' </div>\n');
document.write(' <div class=\"col-md-2 p-0\">\n');
document.write(' <a class=\"btn btn-primary btn-sm btn-block\" href=\"download.html\" target=\"_blank\">Disini</a>\n');
document.write(' </div>\n');
document.write(' </div>\n');
document.write(' <b> </b>\n');
document.write(' </div>\n');
document.write(' <b>\n');
document.write(' <div class=\"alert alert-success\" role=\"alert\">\n');
document.write(' <h4 class=\"alert-heading\">\n');
document.write(' <b>DAFTAR BANK</b>\n');
document.write(' <br>\n');
document.write(' <br> </h4>\n');
document.write(' <p class=\"mb-0 text-left\">Setelah Mendaftar menjadi mitra pulsa kami, langkah selanjutnya adalah deposit pulsa / menambah saldo agar dapat digunakan untuk transaksi semua produk terlengkap dari AGM Pulsa dan PPOB. Harap diperhatikan, cara deposit saldo agen pulsa yang kami terapkan saat ini pastikan nominal harus sama dengan yg didapat melalui TIKET DEPOSIT, jika tidak sama dengan tiket deposit dana kami kembalikan dengan proses manual. <br>\n');
document.write(' <br>\n');
document.write(' <br> </p>\n');
document.write(' <img class=\"d-block img-fluid mx-auto rounded p-2\" src=\"upload/bri.webp\" width=\"134\" height=\"40\">\n');
document.write(' <p class=\"text-center\">\n');
document.write(' <b>002801047027504 : a/n Daniel Corsel</b>\n');
document.write(' <br>\n');
document.write(' <br> </p>\n');
document.write(' <img class=\"img-fluid d-block mx-auto p-2\" src=\"upload/bni.webp\" width=\"134\" height=\"40\">\n');
document.write(' <p class=\"\">\n');
document.write(' <b>0673719166 : a/n Daniel Corsel</b>\n');
document.write(' <br>\n');
document.write(' <br> </p>\n');
document.write(' <img class=\"img-fluid d-block mx-auto p-2\" src=\"upload/mandiri.webp\" width=\"134\" height=\"40\">\n');
document.write(' <p class=\"\">\n');
document.write(' <b>1340013484935 : a/n Daniel Corsel</b>\n');
document.write(' <br>\n');
document.write(' <br> </p>\n');
document.write(' <img class=\"img-fluid d-block p-2 mx-auto\" src=\"upload/bca.webp\" width=\"134\" height=\"40\">\n');
document.write(' <p class=\"\" contenteditable=\"true\">3030596195 : a/n Daniel Corsel <br>\n');
document.write(' <br> </p>\n');
document.write(' </div>\n');
document.write(' </b>\n');
document.write(' </div>\n');
document.write(' <b> </b>\n');
document.write(' </div>\n');
document.write(' <b> </b>\n');
document.write(' </div>\n');
document.write(' <b> </b>\n');
document.write(' </div>\n');
document.write(' <b> </b>\n');
document.write(' </div>\n');
document.write(' <b> </b>\n');
document.write(' </div>');
