document.write( '<div class=\"py-5 text-center\">\n' );
document.write( '      <div class=\"container\">\n' );
document.write( '        <div class=\"row\">\n' );
document.write( '          <div class=\"col-md-12\">\n' );
document.write( '            <div class=\"row\">\n' );
document.write( '              <div class=\"col-md-6\">\n' );
document.write( '                <div class=\"alert alert-secondary\" role=\"alert\">\n' );
document.write( '                  <h4 class=\"alert-heading\">\n' );
document.write( '                    <b>FORMAT TRANSAKSI</b>\n' );
document.write( '                    <br>\n' );
document.write( '                    <br> </h4>\n' );
document.write( '                  <p class=\"mb-0 text-left\">\n' );
document.write( '                    <b>Semua Transaksi dikirim ke Jabber / Telegram / Gtalk / Hangout / SMS Center / Nimbuzz Center.\n' );
document.write( '                      Adapun Format Transaksi yang disediakan adalah sebagai berikut :<br>\n' );
document.write( '                      <br>Format bebas bisa menggunakan karakter :</b><br><b>[ . ] / [ , ] / [ # ] / [ * ] / [\n' );
document.write( '                      sepasi ] / [ Campur ]</b><br><b>Contoh</b><br>Titik : 10.081234567893.1234<br>Koma\n' );
document.write( '                    :10,081234567893,1234<br>Pagar : 10#081234567893#1234<br>Bintang\n' );
document.write( '                    :10*081234567893*1234<br>Sepasi : 10 081234567893 1234<br>Campur : 10#08123456783*1234<br><br></p>\n' );
document.write( '                  <ul class=\"text-left\">\n' );
document.write( '                    <li class=\"text-left\">\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>Daftar Menjadi MASTER</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        DAFTAR#NAMA/KONTER#KOTA</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        DAFTAR#JOKO#JAKARTA</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>Transaksi Isi Pulsa</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        koode.no hp.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        SS10.081234567890.1234</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>Transaksi Token PLN TANPA NO TUJUAN</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        nominal.no token.no hp tujuan.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        PLN20.34012312345.1234</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>Transaksi Token PLN</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        nominal.no token.no hp tujuan.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        PLN20.34012312345.081234567890.1234</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>Transaksi Isi Pulsa Ke No Hp dan Nominal Yang Sama Ke 2,3,4 dst</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        koode.2,3,4,dstno hp.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        SS10.2.081234567890.1234 <span\n' );
document.write( '                          style=\"font-family: arial , helvetica , sans-serif;\"></span>\n' );
document.write( '                      </span>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <span style=\"font-family: arial , helvetica , sans-serif;\"></span>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">Contoh Tanpa\n' );
document.write( '                        kode: 10.3.081234567890.1234</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>Cek Saldo</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        SAL.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        SAL.1234</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>CekSaldo Downline</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        Saldo.id_agen.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        Saldo.AB007.pin</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>Cek Harga</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        CH.KodeProduk.Pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        CH.S.1234</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>Ganti Pin</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        GPIN.pinbaru.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        GPIN.SaMurai7094.1234</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Catatan : PIN\n' );
document.write( '                        Bebas boleh angkan / huruf disarankan kominasi angkahuruf dan panjang agar aman</span>\n' );
document.write( '                      <br> </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>Tambah Hp</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        THP.nomorhpbaru.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        THP.0877412345.1234</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>Daftar Downline</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        REG.nama.alamat.nohpdownline.markup.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        REG.Kios Cell.Bandung.0812222122.50.1234</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>Kirim Saldo</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        TS.id_member.jumlah.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        TS.OK001.200000.5555</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>Cek Status Transaksi</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        CEK.TUJUAN</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        CEK.0812345789</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>Komplain</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        CS.isipesan.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        CS.isi 10rb ke 0812222121 blm mask tgl.18 tolong bntu.1234</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>Tiket Deposit</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        TIKET.Jumlah.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        TIKET.500000.1234</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>BlokirDownline</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        OFF.id_agen.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        OFF.BJ003.pin</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>Buka Blokir</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format\n' );
document.write( '                        :ON.id_agen.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh\n' );
document.write( '                        :ON.BJ003.1234</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>UbahUp/Mark up Harga</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        UBAHMARKUP.id_downline.markup.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        UBAHMARKUP.IN002.100.1234</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>UbahUp/Mark up Perkodeproduk</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        UMP.id_agen.kode-prodak.markup.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        UMP.TE001.S5.50.1234</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>Cek Tagihan PPOB</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        CEK.PLN/ TELKOM/ BPJS/ HALO/ PDAM/ SPEEDY.id_pelanggan.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        CEK.PLN.53531004567699.1234</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>Bayar Tagihan PPOB</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        BAYAR.id_pelanggan.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        BAYAR.535210045676.1234</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>Set Hp Utama</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        HPUTAMA.nomorhpygterdaftar.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        HPUTAMA.0812345454511.pin</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>Hapus Nomor Paralel</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        HAPUSNOHP.nomorparalel.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        HAPUSNOHP.0877788882222.pin</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>Cek Semua Nomor</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        SEMUAHP.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        SEMUAHP.1234</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>Ganti Nama Member</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        GN.namabaru.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        GN.AbadiCell.1234</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>Ambil Bonus REBATE</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        BONUS.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        BONUS.1234</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>ADD JABBER</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        TIM.id/account.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        TIM.joko@jabbim.com/Gf^%GYFRUYFyf.pin</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>ADD TELEGRAMBOT</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        TL.ID telegram.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        TL.212121212.pin</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    \n' );
document.write( '                    <br>\n' );
document.write( '                    <li>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\">\n' );
document.write( '                        <b>ADD WhatsApp / WA</b>\n' );
document.write( '                      </span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Format :\n' );
document.write( '                        WA.NOMER WA.pin</span>\n' );
document.write( '                      <br>\n' );
document.write( '                      <span style=\"font-family: arial , helvetica , sans-serif;\"> Contoh :\n' );
document.write( '                        WA.6281111111112.pin</span>\n' );
document.write( '                    </li>\n' );
document.write( '                    <br>\n' );
document.write( '                  </ul>\n' );
document.write( '                </div>\n' );
document.write( '              </div>\n' );
document.write( '              <div class=\"col-md-6\">\n' );
document.write( '                <div class=\"alert alert-dark\" role=\"alert\">\n' );
document.write( '                  <h4 class=\"alert-heading\">\n' );
document.write( '                    <b>CENTER TRANSAKSI</b>\n' );
document.write( '                    <br>\n' );
document.write( '                    <br> </h4>\n' );
document.write( '                  <p class=\"mb-0 text-left text-dark\">\n' );
document.write( '                    <b>TELEGRAM CHANNEL <br>\n' );
document.write( '                      <a title=\"@agmpulsa\" href=\"https://t.me/agmpulsa\" target=\"_blank\">\n' );
document.write( '                        <span class=\"fa fa-telegram fa-lg\"></span>\n' );
document.write( '                      </a> @agmpulsa</b> <br><br><b>Transaksi Suport</b><br><b>-\n' );
document.write( '                      Aplikasi Android</b><br><b>-\n' );
document.write( '                      Jabber</b><br><b>- Telegram</b><br><b>- WhatsApp/WA</b><br><br><br><b>TELEGRAM CENTER  \n' );
document.write( '                      <br>\n' );
document.write( '                      <a title=\"@agmpulsarobot\" href=\"https://telegram.me/agmpulsarobot\" target=\"_blank\">\n' );
document.write( '                        <span class=\"fa fa-telegram fa-lg\"></span>\n' );
document.write( '                      </a> @agmpulsarobot <br>\n' );
document.write( '                      <a title=\"@ctr1000bot\" href=\"https://telegram.me/ctr1000bot\" target=\"_blank\">\n' );
document.write( '                        <span class=\"fa fa-telegram fa-lg\"></span>\n' );
document.write( '                      </a> @ctr1000bot <br>\n' );
document.write( '                      <a title=\"@ctr2000bot\" href=\"https://telegram.me/ctr2000bot\" target=\"_blank\">\n' );
document.write( '                        <span class=\"fa fa-telegram fa-lg\"></span>\n' );
document.write( '                      </a> @ctr2000bot <br>\n' );
document.write( '                      <a title=\"@ctr3000bot\" href=\"https://telegram.me/ctr3000bot\" target=\"_blank\">\n' );
document.write( '                        <span class=\"fa fa-telegram fa-lg\"></span>\n' );
document.write( '                      </a> @ctr3000bot <br>\n' );
document.write( '                      <a title=\"@ctr4000bot\" href=\"https://telegram.me/ctr4000bot\" target=\"_blank\">\n' );
document.write( '                        <span class=\"fa fa-telegram fa-lg\"></span>\n' );
document.write( '                      </a> @ctr4000bot <br>\n' );
document.write( '\n' );
document.write( '                      <b><br>JABBER / XMPP</b><br>\n' );
document.write( '                      <br>agmpulsa@chat.tigaputri.asia\n' );
document.write( '                        <br>agmpulsa@im.ajs.id<br>agmpulsa@jabber.ru<br>ctragm@xabber.org               \n' );
document.write( '                        <br>\n' );
document.write( '                        <br>WhatsApp / WA<br>\n' );
document.write( '                      6283890625586\n' );
document.write( '                        <br>\n' );
document.write( '                        <br>SMS <br>0895637936618 <br>089652173202 <br>083890625586 <br>\n' );
document.write( '                        <br> </b>\n' );
document.write( '                  </p>\n' );
document.write( '                  <div class=\"row\">\n' );
document.write( '                    <div class=\"col-md-8 text-left text-capitalize\">\n' );
document.write( '                      <p>\n' );
document.write( '                        <b>Download aplikasi pendukung PC / Android</b>\n' );
document.write( '                      </p>\n' );
document.write( '                    </div>\n' );
document.write( '                    <div class=\"col-md-2 p-0\">\n' );
document.write( '                      <a class=\"btn btn-primary btn-sm btn-block\" href=\"download.html\" target=\"_blank\">Disini</a>\n' );
document.write( '                    </div>\n' );
document.write( '                  </div>\n' );
document.write( '                </div>\n' );
document.write( '                <b>\n' );
document.write( '                  <div class=\"alert alert-success\" role=\"alert\">\n' );
document.write( '                    <h4 class=\"alert-heading\">\n' );
document.write( '                      <b>DAFTAR BANK</b>\n' );
document.write( '                      <br>\n' );
document.write( '                      <br> </h4>\n' );
document.write( '                    <p class=\"mb-0 text-left\">Setelah Mendaftar menjadi mitra pulsa kami, langkah selanjutnya adalah\n' );
document.write( '                      deposit pulsa / menambah saldo agar dapat digunakan untuk transaksi semua produk terlengkap dari\n' );
document.write( '                      AGM Pulsa dan PPOB. Harap diperhatikan, cara deposit saldo agen pulsa yang kami terapkan saat ini\n' );
document.write( '                      pastikan nominal harus sama dengan yg didapat melalui TIKET DEPOSIT, jika tidak sama dengan tiket\n' );
document.write( '                      deposit dana kami kembalikan dengan proses manual. <br>\n' );
document.write( '                      <br>\n' );
document.write( '                      <br> </p>\n' );
document.write( '                    <img class=\"d-block img-fluid mx-auto rounded p-2\" src=\"upload/bri.jpg\" width=\"134\" height=\"40\">\n' );
document.write( '                    <p class=\"text-center\">\n' );
document.write( '                      <b>002801047027504 : a/n Daniel Corsel</b>\n' );
document.write( '                      <br>\n' );
document.write( '                      <br> </p>\n' );
document.write( '                    <img class=\"img-fluid d-block mx-auto p-2\" src=\"upload/bni.jpg\" width=\"134\" height=\"40\">\n' );
document.write( '                    <p class=\"\">\n' );
document.write( '                      <b>0673719166 : a/n Daniel Corsel</b>\n' );
document.write( '                      <br>\n' );
document.write( '                      <br> </p>\n' );
document.write( '                    <img class=\"img-fluid d-block mx-auto p-2\" src=\"upload/mandiri.jpg\" width=\"134\" height=\"40\">\n' );
document.write( '                    <p class=\"\">\n' );
document.write( '                      <b>1340013484935 : a/n Daniel Corsel</b>\n' );
document.write( '                      <br>\n' );
document.write( '                      <br> </p>\n' );
document.write( '                    <img class=\"img-fluid d-block p-2 mx-auto\" src=\"upload/bca.jpg\" width=\"134\" height=\"40\">\n' );
document.write( '                    <p class=\"\" contenteditable=\"true\">3030596195 : a/n Daniel Corsel <br>\n' );
document.write( '                      <br> </p>\n' );
document.write( '                  </div>\n' );
document.write( '                </b>\n' );
document.write( '              </div>\n' );
document.write( '            </div>\n' );
document.write( '          </div>\n' );
document.write( '        </div>\n' );
document.write( '      </div>\n' );
document.write( '    </div>' );
