document.writeln(" <div class=\"bg-hitamdasar\"> ");
document.writeln("         <div class=\"container\"> ");
document.writeln("           <div class=\"row\"> ");
document.writeln("             <div class=\"p-4 col-md-4\"> ");
document.writeln("               <h3 class=\"mb-4 text-white\"> ");
document.writeln("                 <b>Cara Pendaftaran Master</b> ");
document.writeln("               </h3> ");
document.writeln("               <p class=\"text-white\"> ");
document.writeln("                 <sp style=\"font-weight: normal;\">FORMAT :&nbsp; <br>DAFTAR#NAMA/KONTER#KOTA&nbsp; <br>Contoh : <br>DAFTAR#JOKO#JAKARTA&nbsp;<br>Kirim Ke Center :&nbsp;<br>089-5415-091175<br>083-8906-25586<br>085-9121-530712</sp> ");
document.writeln("               </p> ");
document.writeln("             </div> ");
document.writeln("             <div class=\"col-md-4 p-4\"> ");
document.writeln("               <h3 class=\"mb-4 text-white\"> ");
document.writeln("                 <b>Map Site</b> ");
document.writeln("               </h3> ");
document.writeln("               <ul class=\"list-unstyled\"> ");
document.writeln("                 <a href=\"https://aksesglobalmultimedia.com/index.html\" class=\"text-white\">Home</a> ");
document.writeln("                 <br> ");
document.writeln("                 <a href=\"https://aksesglobalmultimedia.com/daftar-harga.html\" class=\"text-white\">Dafter Harga</a> ");
document.writeln("                 <br> ");
document.writeln("                 <a href=\"https://aksesglobalmultimedia.com/cara-transaksi.html\" class=\"text-white\">Cara Transaksi</a> ");
document.writeln("                 <br> ");
document.writeln("                 <a href=\"https://aksesglobalmultimedia.com/download.html\" class=\"text-white\">Download</a> ");
document.writeln("                 <br> ");
document.writeln("                 <a href=\"https://aksesglobalmultimedia.com/berita.html\" class=\"text-white\">Berita</a> ");
document.writeln("                 <br> ");
document.writeln("                 <a href=\"https://aksesglobalmultimedia.com/karir.html\" class=\"text-white\">Karir</a> ");
document.writeln("                 <br> ");
document.writeln("                 <a href=\"#\" class=\"text-white\">Web Reporting</a> ");
document.writeln("                 <br> ");
document.writeln("                 <a href=\"https://aksesglobalmultimedia.com/kontak-kami.html\" class=\"text-white\">Kontak Kami</a> ");
document.writeln("               </ul> ");
document.writeln("             </div> ");
document.writeln("             <div class=\"p-4 col-md-4\"> ");
document.writeln("               <h3 class=\"mb-4 text-white\"> ");
document.writeln("                 <b>Contact</b> ");
document.writeln("               </h3> ");
document.writeln("               <p> ");
document.writeln("                 <a href=\"tel:+6285642100966\" class=\"text-white\" style=\"font-weight: normal;\"> ");
document.writeln("                   <i class=\"fa d-inline mr-3 text-secondary fa-phone\"></i>0856 4210 0966</a> ");
document.writeln("               </p> ");
document.writeln("               <p> ");
document.writeln("                 <a href=\"mailto:infoaksesglobal@gmail.com\" class=\"text-white\" style=\"font-weight: normal;\"> ");
document.writeln("                   <i class=\"fa d-inline mr-3 text-secondary fa-envelope-o\"></i>infoaksesglobal@gmail.com</a> ");
document.writeln("               </p> ");
document.writeln("               <p> ");
document.writeln("                 <span style=\"font-weight: normal;\"><a href=\"https://goo.gl/maps/ibp421n94d32\" class=\"text-white\" target=\"_blank\" style=\"\"> ");
document.writeln("                     <i class=\"fa d-inline mr-3 fa-map-marker text-secondary\"></i> Jl Gunung rinjani Blok 8 No 11 Perum Margalaksana 1 Indramayu</a> ");
document.writeln("                 </span><br> </p> ");
document.writeln("             </div> ");
document.writeln("           </div> ");
document.writeln("           <div class=\"row\"> ");
document.writeln("             <div class=\"col-md-12 mt-3\"> ");
document.writeln("               <p class=\"text-center text-white\"><span style=\"font-weight: normal;\">© Copyright 2019 <a style=\"color:with\" href=\"https://aksesglobalmultimedia.com/\" target=\"_blank\">AGM Pulsa dan PPOB</a> - All rights reserved. </span></p> ");
document.writeln("             </div> ");
document.writeln("           </div> ");
document.writeln("         </div> ");
document.writeln("       </div> ");