document.write( '<div class=\"p-4\" >\n' );
document.write( '      <div class=\"container\">\n' );
document.write( '        <div class=\"row\">\n' );
document.write( '          <div class=\"col-md-6\">\n' );
document.write( '            <a class=\"btn btn-facebook btn-block m-2\" href=\"#\">Cara Daftar Menjadi Mitra</a>\n' );
document.write( '            <a class=\"btn btn-facebook btn-block m-2\" href=\"#\">Cara Daftar Menjadi Mitra H2H</a>\n' );
document.write( '            <a class=\"btn btn-facebook btn-block m-2\" href=\"http://aksesglobalmultimedia.com/deposit.html\">Cara Deposit Saldo</a>\n' );
document.write( '          </div>\n' );
document.write( '          <div class=\"col-md-6\">\n' );
document.write( '            <a class=\"btn btn-facebook btn-block m-2\" href=\"http://aksesglobalmultimedia.com/seting-telegram.html\">Cara Seting Telegram</a>\n' );
document.write( '            <a class=\"btn btn-facebook btn-block m-2\" href=\"#\">Cara Seting GTalk / Hangout</a>\n' );
document.write( '            <a class=\"btn btn-facebook btn-block m-2\" href=\"https://www.youtube.com/results?search_query=jabber+agm+pulsa\">Cara Seting Jabber</a>\n' );
document.write( '          </div>\n' );
document.write( '        </div>\n' );
document.write( '      </div>\n' );
document.write( '    </div>' );
