document.write( '<div class=\"p-4\" >\n' );
document.write( '      <div class=\"container\">\n' );
document.write( '        <div class=\"row\">\n' );
document.write( '          <div class=\"col-md-6\">\n' );
document.write( '            <a class=\"btn btn-facebook btn-block m-2\" href=\"#\">Cara Daftar Menjadi Mitra</a>\n' );
document.write( '            <a class=\"btn btn-facebook btn-block m-2\" href=\"#\">Cara Daftar Menjadi Mitra H2H</a>\n' );
document.write( '            <a class=\"btn btn-facebook btn-block m-2\" href=\"http://aksesglobalmultimedia.com/deposit.html\">Cara Deposit Saldo</a>\n' );
document.write( '          </div>\n' );
document.write( '          <div class=\"col-md-6\">\n' );
document.write( '            <a class=\"btn btn-facebook btn-block m-2\" href=\"http://aksesglobalmultimedia.com/seting-telegram.html\">Cara Seting Telegram</a>\n' );
document.write( '            <a class=\"btn btn-facebook btn-block m-2\" href=\"#\">Cara Seting GTalk / Hangout</a>\n' );
document.write( '            <a class=\"btn btn-facebook btn-block m-2\" href=\"https://www.youtube.com/results?search_query=jabber+agm+pulsa\">Cara Seting Jabber</a>\n' );
document.write( '          </div>\n' );
document.write( '        </div>\n' );
document.write( '      </div>\n' );
document.write( '    </div>' );
document.write("<br><center><script async src=/"https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js/"></script>");
document.write("<ins class=/"adsbygoogle/"");
document.write("     style=/"display:block/"");
document.write("     data-ad-client=/"ca-pub-4116213103941802/"");
document.write("     data-ad-slot=/"2795192372/"");
document.write("     data-ad-format=/"auto/"");
document.write("     data-full-width-responsive=/"true/"></ins>");
document.write("<script>");
document.write("     (adsbygoogle = window.adsbygoogle || []).push({});");
document.write("</script></center><br>");