document.writeln(" <div class=\"p-4\"> "); 
document.writeln("       <div class=\"container\"> "); 
document.writeln("         <div class=\"row\"> "); 
document.writeln("           <div class=\"col-md-6\"> "); 
document.writeln("             <a class=\"btn btn-facebook btn-block m-2\" href=\"https://aksesglobalmultimedia.com/daftar-master-h2h.html\">Cara Daftar Menjadi Mitra</a> "); 
document.writeln("             <a class=\"btn btn-facebook btn-block m-2\" href=\"https://aksesglobalmultimedia.com/daftar-master-h2h.html\">Cara Daftar Menjadi Mitra H2H</a> "); 
document.writeln("             <a class=\"btn btn-facebook btn-block m-2\" href=\"https://aksesglobalmultimedia.com/deposit.html\">Cara Deposit Saldo</a> "); 
document.writeln("           </div> "); 
document.writeln("           <div class=\"col-md-6\"> "); 
document.writeln("             <a class=\"btn btn-facebook btn-block m-2\" href=\"https://aksesglobalmultimedia.com/seting-telegram.html\">Cara Seting Telegram</a> "); 
document.writeln("             <a class=\"btn btn-facebook btn-block m-2\" href=\"https://aksesglobalmultimedia.com/cara-seting-gtalk.html\">Cara Seting GTalk / Hangout</a> "); 
document.writeln("             <a class=\"btn btn-facebook btn-block m-2\" href=\"https://aksesglobalmultimedia.com/cara-seting-jabber.html\">Cara Seting Jabber</a> "); 
document.writeln("           </div> "); 
document.writeln("         </div> "); 
document.writeln("       </div> "); 
document.writeln("     </div> ");