document.writeln(" <nav class=\"navbar navbar-expand-md bg-secondary border fixed-top navbar-dark\"> "); 
document.writeln("     <div class=\"container\"> "); 
document.writeln("       <button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"> "); 
document.writeln("         <span class=\"navbar-toggler-icon\"></span> "); 
document.writeln("       </button> "); 
document.writeln("       <a class=\"navbar-brand\" href=\"http://aksesglobalmultimedia.com/"> "); 
document.writeln("         <img src=\"http://aksesglobalmultimedia.com/upload/logo.png\" width=\"149\" height=\"57\" class=\"d-inline-block align-top\" alt=\"agm pulsa dan ppob\"> </a> "); 
document.writeln("       <div class=\"collapse navbar-collapse justify-content-start\" id=\"navbarSupportedContent\"> "); 
document.writeln("         <ul class=\"navbar-nav ml-auto p-2\"> "); 
document.writeln("           <b> "); 
document.writeln("             <li class=\"nav-item\"> "); 
document.writeln("               <a class=\"nav-link \" href=\"http://aksesglobalmultimedia.com/pulsa.html\"> "); 
document.writeln("                 <i class=\"fa fa-home fa-lg\"></i> "); 
document.writeln("                 <b>Home</b> "); 
document.writeln("               </a> "); 
document.writeln("             </li> "); 
document.writeln("           </b> "); 
document.writeln("           <b> "); 
document.writeln("             <li class=\"nav-item\"> "); 
document.writeln("               <a class=\"nav-link\" href=\"http://aksesglobalmultimedia.com/daftar-master-h2h.html\"> "); 
document.writeln("                 <b>Pendaftaran</b> "); 
document.writeln("               </a> "); 
document.writeln("             </li> "); 
document.writeln("           </b> "); 
document.writeln("           <b> "); 
document.writeln("             <li class=\"nav-item\"> "); 
document.writeln("               <a class=\"nav-link \" href=\"http://aksesglobalmultimedia.com/daftar-harga.html\"> "); 
document.writeln("                 <b>Harga Produk</b> "); 
document.writeln("               </a> "); 
document.writeln("             </li> "); 
document.writeln("           </b> "); 
document.writeln("           <b> "); 
document.writeln("             <li class=\"nav-item dropdown\"> "); 
document.writeln("               <a class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\"><b>Panduan Transaksi</b></a> "); 
document.writeln("               <div class=\"dropdown-menu\"> "); 
document.writeln("                 <a class=\"dropdown-item\" href=\"http://aksesglobalmultimedia.com/cara-transaksi.html\"><b>Format Transaksi</b></a> "); 
document.writeln("                 <a class=\"dropdown-item\" href=\"http://aksesglobalmultimedia.com/daftar-master-h2h.html\"><b>Cara Daftar Master MD / H2H</b></a> "); 
document.writeln("                 <a class=\"dropdown-item\" href=\"http://aksesglobalmultimedia.com/persing-h2h.html\"><b>Seting H2H</b></a> "); 
document.writeln("                 <a class=\"dropdown-item\" href=\"http://aksesglobalmultimedia.com/deposit.html\"><b>Cara Deposit</b></a> "); 
document.writeln("                 <a class=\"dropdown-item\" href=\"http://aksesglobalmultimedia.com/seting-telegram.html\"><b>Cara Seting Telegram</b></a> "); 
document.writeln("                 <a class=\"dropdown-item\" href=\"http://aksesglobalmultimedia.com/cara-seting-jabber.html\"><b>Cara Seting Jabber</b></a> "); 
document.writeln("                 <a class=\"dropdown-item\" href=\"http://aksesglobalmultimedia.com/cara-seting-gtalk.html\"><b>Cara Seting Gtalk</b></a> "); 
document.writeln("                 <div class=\"dropdown-divider\"></div> "); 
document.writeln("                 <a class=\"dropdown-item\" href=\"http://aksesglobalmultimedia.com/daftar-telegram.html\"><b>Cara Daftar Akun Telegram</b></a> "); 
document.writeln("                 <a class=\"dropdown-item\" href=\"http://aksesglobalmultimedia.com/verifikasi-dua-langkah-telegram.html\"><b>Cara Amankan Akun Telegram</b></a> "); 
document.writeln("               </div> "); 
document.writeln("             </li> "); 
document.writeln("           </b> "); 
document.writeln("           <b> "); 
document.writeln("             <li class=\"nav-item\"> "); 
document.writeln("               <a class=\"nav-link\" href=\"http://aksesglobalmultimedia.com/download.html\"> "); 
document.writeln("                 <b>Download</b> "); 
document.writeln("               </a> "); 
document.writeln("             </li> "); 
document.writeln("           </b> "); 
document.writeln("           <b> "); 
document.writeln("             <li class=\"nav-item\"> "); 
document.writeln("               <a class=\"nav-link\" target=\"_blank\" href=\"http://aksesglobalmultimedia.com/webreporttgr.html\"><b>Web Reporting</b></a> "); 
document.writeln("             </li> "); 
document.writeln("           </b> "); 
document.writeln("           <b> "); 
document.writeln("             <li class=\"nav-item\"> "); 
document.writeln("               <a class=\"nav-link\" href=\"http://aksesglobalmultimedia.com/kontak-kami.html\"> "); 
document.writeln("                 <b>Kontak Kami</b> "); 
document.writeln("               </a> "); 
document.writeln("             </li> "); 
document.writeln("           </b> "); 
document.writeln("         </ul> "); 
document.writeln("       </div> "); 
document.writeln("     </div> "); 
document.writeln("   </nav> ");