document.write('<nav class=\"navbar navbar-expand-md bg-secondary border fixed-top navbar-dark\" >\n');
document.write(' <div class=\"container\">\n');
document.write(' <button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\">\n');
document.write(' <span class=\"navbar-toggler-icon\"></span>\n');
document.write(' </button>\n');
document.write(' <a class=\"navbar-brand\" href=\"http://aksesglobalmultimedia.com/index.html\">\n');
document.write(' <img src=\"upload/logo.webp\" width=\"149\" height=\"57\" class=\"d-inline-block align-top\" alt=\"agm pulsa dan ppob\"> </a>\n');
document.write(' <div class=\"collapse navbar-collapse justify-content-start\" id=\"navbarSupportedContent\">\n');
document.write(' <ul class=\"navbar-nav ml-auto p-2\">\n');
document.write(' <b>\n');
document.write(' <li class=\"nav-item\">\n');
document.write(' <a class=\"nav-link \" href=\"http://aksesglobalmultimedia.com/pulsa.html\">\n');
document.write(' <i class=\"fa fa-home fa-lg\"></i>\n');
document.write(' <b>Home</b>\n');
document.write(' </a>\n');
document.write(' </li>\n');
document.write(' </b>\n');
document.write(' <b>\n');
document.write(' <li class=\"nav-item\">\n');
document.write(' <a class=\"nav-link \" href=\"http://aksesglobalmultimedia.com/daftar-harga.html\">\n');
document.write(' <b>Daftar Harga</b>\n');
document.write(' </a>\n');
document.write(' </li>\n');
document.write(' </b>\n');
document.write(' <b>\n');
document.write('            <li class=\"nav-item dropdown\">');
document.write('              <a class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\"><b>Cara Transaksi</b></a>');
document.write('              <div class=\"dropdown-menu\">');
document.write('                <a class=\"dropdown-item\" href=\"http://aksesglobalmultimedia.com/cara-transaksi.html\"><b>Format Transaksi</b></a>');
document.write('                <a class=\"dropdown-item\" href=\"http://aksesglobalmultimedia.com/daftar-master-h2h.html\"><b>Cara Daftar Master MD / H2H</b></a>');
document.write('                <a class=\"dropdown-item\" href=\"http://aksesglobalmultimedia.com/persing-h2h.html\"><b>Seting H2H</b></a>');
document.write('                <a class=\"dropdown-item\" href=\"http://aksesglobalmultimedia.com/deposit.html\"><b>Cara Deposit</b></a>');
document.write('                <a class=\"dropdown-item\" href=\"http://aksesglobalmultimedia.com/seting-telegram.html\"><b>Cara Seting Telegram</b></a>');
document.write('                <a class=\"dropdown-item\" href=\"http://aksesglobalmultimedia.com/cara-seting-jabber.html\"><b>Cara Seting Jabber</b></a>');
document.write('                <a class=\"dropdown-item\" href=\"http://aksesglobalmultimedia.com/cara-seting-gtalk.html\"><b>Cara Seting Gtalk</b></a>');
document.write('                <div class=\"dropdown-divider\"></div>');
document.write('                <a class=\"dropdown-item\" href=\"http://aksesglobalmultimedia.com/daftar-telegram.html\"><b>Cara Daftar Akun Telegram</b></a>');
document.write('                <a class=\"dropdown-item\" href=\"http://aksesglobalmultimedia.com/verifikasi-dua-langkah-telegram.html\"><b>Cara Amankan Akun Telegram</b></a>');
document.write('              </div>');
document.write('            </li>');
document.write(' </b>\n');
document.write(' <b>\n');
document.write(' <li class=\"nav-item\">\n');
document.write(' <a class=\"nav-link\" href=\"http://aksesglobalmultimedia.com/download.html\">\n');
document.write(' <b>Download</b>\n');
document.write(' </a>\n');
document.write(' </li>\n');
document.write(' </b>\n');
document.write(' <b>\n');
document.write(' <li class=\"nav-item\">\n');
document.write(' <a class=\"nav-link\" href=\"http://aksesglobalmultimedia.com/berita.html\">\n');
document.write(' <b>Berita</b>\n');
document.write(' </a>\n');
document.write(' </li>\n');
document.write(' </b>\n');
document.write(' <b>\n');
document.write(' <li class=\"nav-item\">\n');
document.write(' <a class=\"nav-link\" href=\"http://aksesglobalmultimedia.com/karir.html\">\n');
document.write(' <b>Karir</b>\n');
document.write(' </a>\n');
document.write(' </li>\n');
document.write(' </b>\n');
document.write(' <b>\n');
document.write(' <li class=\"nav-item\">\n');
document.write(' <a class=\"nav-link\" target=\"_blank\" href=\"http://aksesglobalmultimedia.com/webreporttgr.html\"><b>Web Reporting</b></a>\n');
document.write(' </li>\n');
document.write(' </b>\n');
document.write(' <b>\n');
document.write(' <li class=\"nav-item\">\n');
document.write(' <a class=\"nav-link\" href=\"http://aksesglobalmultimedia.com/kontak-kami.html\">\n');
document.write(' <b>Kontak Kami</b>\n');
document.write(' </a>\n');
document.write(' </li>\n');
document.write(' </b>\n');
document.write(' </ul>\n');
document.write(' <b> </b>\n');
document.write(' </div>\n');
document.write(' <b> </b>\n');
document.write(' </div>\n');
document.write(' <b> </b>\n');
document.write(' </nav>');
