document.write( '<div class=\"bg-hitamdasar\" >\n' );
document.write( '        <div class=\"container\">\n' );
document.write( '          <div class=\"row\">\n' );
document.write( '            <div class=\"p-4 col-md-4\">\n' );
document.write( '              <h3 class=\"mb-4 text-white\">\n' );
document.write( '                <b>Cara Pendaftaran Master</b>\n' );
document.write( '              </h3>\n' );
document.write( '              <p class=\"text-white\">\n' );
document.write( '                <sp style=\"font-weight: normal;\">FORMAT :  <br>DAFTAR#NAMA/KONTER#KOTA  <br>Contoh : <br>DAFTAR#JOKO#JAKARTA <br>Kirim Ke Center : <br>0895-6379-36618<br>0838-9062-5586<br>0838-9062-5586</sp>\n' );
document.write( '              </p>\n' );
document.write( '            </div>\n' );
document.write( '            <div class=\"col-md-4 p-4\">\n' );
document.write( '              <h3 class=\"mb-4 text-white\">\n' );
document.write( '                <b>Map Site</b>\n' );
document.write( '              </h3>\n' );
document.write( '              <ul class=\"list-unstyled\">\n' );
document.write( '                <span style=\"font-weight: normal;\"><a href=\"https://aksesglobalmultimedia.com/index.html\" class=\"text-white\">Home</a>\n' );
document.write( '                  <br>\n' );
document.write( '                  <a href=\"http://8.219.188.200:6968\" class=\"text-white\">Dafter Harga</a>\n' );
document.write( '                  <br>\n' );
document.write( '                  <a href=\"https://aksesglobalmultimedia.com/cara-transaksi.html\" class=\"text-white\">Cara Transaksi</a>\n' );
document.write( '                  <br>\n' );
document.write( '                  <a href=\"https://aksesglobalmultimedia.com/download.html\" class=\"text-white\">Download</a>\n' );
document.write( '                  <br>\n' );
document.write( '                  <a href=\"https://aksesglobalmultimedia.com/berita.html\" class=\"text-white\">Berita</a>\n' );
document.write( '                  <br>\n' );
document.write( '                  <a href=\"https://aksesglobalmultimedia.com/karir.html\" class=\"text-white\">Karir</a>\n' );
document.write( '                  <br>\n' );
document.write( '                  <a href=\"https://aksesglobalmultimedia.com/webreporttgr.html\" class=\"text-white\">Web Reporting</a>\n' );
document.write( '                  <br>\n' );
document.write( '                  <a href=\"https://aksesglobalmultimedia.com/kontak-kami.html\" class=\"text-white\">Kontak Kami</a></span>\n' );
document.write( '              </ul>\n' );
document.write( '            </div>\n' );
document.write( '            <div class=\"p-4 col-md-4\">\n' );
document.write( '              <h3 class=\"mb-4 text-white\">\n' );
document.write( '                <b>Contact</b>\n' );
document.write( '              </h3>\n' );
document.write( '              <p>\n' );
document.write( '                <a href=\"https://telegram.me/csagm\" class=\"text-white\" target=\"_blank\" style=\"font-weight: normal;\">\n' );
document.write( '                  <i class=\"fa d-inline mr-3 text-secondary fa-telegram\"></i>+62895373048830 = @csagm</a>\n' );
document.write( '              </p>\n' );
document.write( '              <p>\n' );
document.write( '                <a href=\"tel:+6285642100966\" class=\"text-white\" style=\"font-weight: normal;\">\n' );
document.write( '                  <i class=\"fa d-inline mr-3 text-secondary fa-phone\"></i>0856 4210 0966</a>\n' );
document.write( '              </p>\n' );
document.write( '              <p>\n' );
document.write( '                <a href=\"mailto:infoaksesglobal@gmail.com\" class=\"text-white\" style=\"font-weight: normal;\">\n' );
document.write( '                  <i class=\"fa d-inline mr-3 text-secondary fa-envelope-o\"></i>infoaksesglobal@gmail.com</a>\n' );
document.write( '              </p>\n' );
document.write( '              <p>\n' );
document.write( '                <span style=\"font-weight: normal;\"><a href=\"https://goo.gl/maps/ibp421n94d32\" class=\"text-white\" target=\"_blank\" style=\"\">\n' );
document.write( '                    <i class=\"fa d-inline mr-3 fa-map-marker text-secondary\"></i> Jl Gunung rinjani Blok 8 No 11 Perum Margalaksana 1 Indramayu</a>\n' );
document.write( '                </span><br> </p>\n' );
document.write( '            </div>\n' );
document.write( '          </div>\n' );
document.write( '          <div class=\"row\">\n' );
document.write( '            <div class=\"col-md-12 mt-3\">\n' );
document.write( '              <p class=\"text-center text-white\"><span style=\"font-weight: normal;\">© Copyright 2019 <a style=\"color:with\" href=\"https://aksesglobalmultimedia.com/index.html\" target=\"_blank\">AGM Pulsa dan PPOB</a> - All rights reserved. </span></p>\n' );
document.write( '            </div>\n' );
document.write( '          </div>\n' );
document.write( '        </div>\n' );
document.write( '      </div>' );
