document.write( '<nav class=\"navbar navbar-expand-md bg-secondary border fixed-top navbar-dark\" >\n' );
document.write( '    <div class=\"container\">\n' );
document.write( '      <button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\">\n' );
document.write( '        <span class=\"navbar-toggler-icon\"></span>\n' );
document.write( '      </button>\n' );
document.write( '      <a class=\"navbar-brand\" href=\"index.html\">\n' );
document.write( '        <img src=\"upload/logo.png\" width=\"149\" height=\"57\" class=\"d-inline-block align-top\" alt=\"agm pulsa dan ppob\"> </a>\n' );
document.write( '      <div class=\"collapse navbar-collapse justify-content-start\" id=\"navbarSupportedContent\">\n' );
document.write( '        <ul class=\"navbar-nav ml-auto p-2\">\n' );
document.write( '          <b>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '              <a class=\"nav-link \" href=\"pulsa.html\">\n' );
document.write( '                <i class=\"fa fa-home fa-lg\"></i>\n' );
document.write( '                <b>Home</b>\n' );
document.write( '              </a>\n' );
document.write( '            </li>\n' );
document.write( '          </b>\n' );
document.write( '          <b>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '              <a class=\"nav-link \" href=\"daftar-harga.html\">\n' );
document.write( '                <b>Daftar Harga</b>\n' );
document.write( '              </a>\n' );
document.write( '            </li>\n' );
document.write( '          </b>\n' );
document.write( '          <b>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '              <a class=\"nav-link\" href=\"cara-transaksi.html\">\n' );
document.write( '                <b>Cara Transaksi</b>\n' );
document.write( '              </a>\n' );
document.write( '            </li>\n' );
document.write( '          </b>\n' );
document.write( '          <b>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '              <a class=\"nav-link\" href=\"download.html\">\n' );
document.write( '                <b>Download</b>\n' );
document.write( '              </a>\n' );
document.write( '            </li>\n' );
document.write( '          </b>\n' );
document.write( '          <b>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '              <a class=\"nav-link\" href=\"berita.html\">\n' );
document.write( '                <b>Berita</b>\n' );
document.write( '              </a>\n' );
document.write( '            </li>\n' );
document.write( '          </b>\n' );
document.write( '          <b>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '              <a class=\"nav-link\" href=\"karir.html\">\n' );
document.write( '                <b>Karir</b>\n' );
document.write( '              </a>\n' );
document.write( '            </li>\n' );
document.write( '          </b>\n' );
document.write( '          <b>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '              <a class=\"nav-link\" target=\"_blank\" href=\"webreporttgr.html\"><b>Web Reporting</b></a>\n' );
document.write( '            </li>\n' );
document.write( '          </b>\n' );
document.write( '          <b>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '              <a class=\"nav-link\" href=\"kontak-kami.html\">\n' );
document.write( '                <b>Kontak Kami</b>\n' );
document.write( '              </a>\n' );
document.write( '            </li>\n' );
document.write( '          </b>\n' );
document.write( '        </ul>\n' );
document.write( '        <b> </b>\n' );
document.write( '      </div>\n' );
document.write( '      <b> </b>\n' );
document.write( '    </div>\n' );
document.write( '    <b> </b>\n' );
document.write( '  </nav>' );
