document.write( '<!-- m3u8 Video -->\n' );
document.write( '          <video id=\"hls-example\" class=\"video-js vjs-default-skin\" width=\"100%\" height=\"300\" controls=\"\" >\n' );
document.write( '            <source type=\"application/x-mpegURL\" src=\"http://moiptvhls-i.akamaihd.net/hls/live/652314/HQs/chunklist.m3u8\">\n' );
document.write( '          </video>\n' );
document.write( '          <!-- JS code -->\n' );
document.write( '          <!-- If you\'d like to support IE8 (for Video.js versions prior to v7) -->\n' );
document.write( '          <script src=\"https://vjs.zencdn.net/ie8/ie8-version/videojs-ie8.min.js\" style=\"\"></script>\n' );
document.write( '          <script src=\"videojs-contrib-hls.js\" type=\"text/javascript\"></script>\n' );
document.write( '          <script src=\"video.js\" type=\"text/javascript\" style=\"\"></script>\n' );
document.write( '          <script>\n' );
document.write( '            var player = videojs(\'hls-example\');\n' );
document.write( '            player.play();\n' );
document.write( '          </script>\n' );
document.write( '          <!-- m3u8 Video -->' );
