var kata_bijak=new Array()
kata_bijak[0]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Seseorang yang luar biasa itu sederhana dalam ucapannya, Tetapi hebat dalam tindakanya  <br><br>-- Ibadah Online --</a>";
kata_bijak[1]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Suatu hal yang patut menjadi kebanggaan adalah ketika seseorang memutuskan untuk menjadi dirinya sendiri.  <br><br>-- Ibadah Online --</a>";
kata_bijak[2]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Agar masa depanmu lebih baik maka berusahalah mulai dari sekarang.  <br><br>-- Ibadah Online --</a>";
kata_bijak[3]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Masa depan bukanlah tujuan utama, melainkan perbaikan melalui tindakan yang benar – benar nyata. <br><br>-- Ibadah Online --</a>";
kata_bijak[4]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Kamu harus mengetahui tujuan utama masa depanmu, agar kamu tahu sepenuhnya tujuan hidupmu. <br><br>-- Ibadah Online --</a>";
kata_bijak[5]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Merupakan suatu hal yang sangat sukar ketika semua yang awalnya baik tiba - tiba berubah menjadi buruk. Dan yang lebih sukar dari itu adalah memilih sebuah pilihan antara melepaskan atau tetap bertahan. <br><br>-- Ibadah Online --</a>";
kata_bijak[6]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Ketika kamu bermimpi, jagan pernah takut untuk bermimpi setinggi – tingginya, karena ketka Tuhan berkehendak engkau bermimpi setinggi – tingginya, berarti Dia pun berkehendak bahwa kamu bisa mewujudkannya. <br><br>-- Ibadah Online --</a>";
kata_bijak[7]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Teruslah percaya dan bekerja keraslah <br><br>-- Ibadah Online --</a>";
kata_bijak[8]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Jika bisa menjadi sukses sewaktu muda, kenapa harus menunggu usia tua? <br><br>-- Ibadah Online --</a>";
kata_bijak[9]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Kurang pandai mungkin bisa di perbaiki, tapi kejujuran tidak akan pernah mudah untuk di tanamkan <br><br>-- Ibadah Online --</a>";
kata_bijak[10]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Jangan hanya memandang dari salah satu sisi, agar pandanganmu tidak tersempitkan <br><br>-- Ibadah Online --</a>";
kata_bijak[11]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Jauhilah orang yang banyak berfikir negative karena dari sana akan muncul masalah dari sebuah solusi yang ada <br><br>-- Ibadah Online --</a>";
kata_bijak[12]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Dengan bekerja keras engkau akan mengalahkan orang – orang yang berbakat <br><br>-- Ibadah Online --</a>";
kata_bijak[13]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Ketika kamu memiliki keyakinan untuk mampu melakukan maka kamu akan bisa mewujudkan segala mimpimu <br><br>-- Ibadah Online --</a>";
kata_bijak[14]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Orang yang bertindak tanpa berpikir adalah orang yang gagal <br><br>-- Ibadah Online --</a>";
kata_bijak[15]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Gagal adalah masalah kecil namun putus asa adalah masalah yang besar <br><br>-- Ibadah Online --</a>";
kata_bijak[16]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Sebuah langkah kecil adalah sebuah awal jalan yang panjang <br><br>-- Ibadah Online --</a>";
kata_bijak[17]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Tekuni salah satu bidang maka Anda akan menjadi orang hebat yang berhasil <br><br>-- Ibadah Online --</a>";
kata_bijak[18]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>harapan dan keinginan ini semestinya sejalan, yah sejalan dengan seberapa besar usaha ia dalam mewujudkannya <br><br>-- Ibadah Online --</a>";
kata_bijak[19]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Seorang juara pasti akan percaya pada dirinya sendiri, walaupun tidak ada orang yang mau mempercayainya lagi <br><br>-- Ibadah Online --</a>";
kata_bijak[20]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Ketakutan harus dikerdilkan, karena ketakutan adalah musuh besar impian yang akan diwujudkan <br><br>-- Ibadah Online --</a>";
kata_bijak[21]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Kerja keras orang tua itu karena ingin anak – anaknya menjadi pribadi yang bukan hanya biasa tapi luar biasa <br><br>-- Ibadah Online --</a>";
kata_bijak[22]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Saat orang lain disekitarmu berkata bahwa dirimu telah berubah, sebenarnya hanyalah engkau mulai berhenti untuk tidak melakukan hal – hal yang sperti biasanya mereka ingin Anda melakukannya. <br><br>-- Ibadah Online --</a>";
kata_bijak[23]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Agar langkah sukses Ada 10 kali lebih cepat, maka Anda perlu mempunyai keberanian untuk mengambil keputusan. <br><br>-- Ibadah Online --</a>";
kata_bijak[24]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Kesuksesan akan sangat jauh, apabila Anda bayak melakukan hal – hal yang sia – sia. <br><br>-- Ibadah Online --</a>";
kata_bijak[25]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Sebuah keputusan yang paling baik ialah dengan berpedoman pengalaman hidup. Dan pengalaman hidup diperoleh dari keputusan yang pernah salah <br><br>-- Ibadah Online --</a>";
kata_bijak[26]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Setiap hari sangatlah berharga, janganlah menunggu waktu yang tepat untuk mulai melangkah. <br><br>-- Ibadah Online --</a>";
kata_bijak[27]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Sebuah keberuntunga akn datang ketika Anda dapat mengambil peluang dan kesempatan dengan persiapan yang matang <br><br>-- Ibadah Online --</a>";
kata_bijak[28]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Sikap Anda saat ini adalah bentuk dari pengalaman hidup Anda <br><br>-- Ibadah Online --</a>";
kata_bijak[29]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Waktu sangatlah berharga, janganlah pernah menyia – nyiakannya <br><br>-- Ibadah Online --</a>";
kata_bijak[30]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Waktu itu ibarat pedang yang bila digunakan dengan baik akan membwamu pada sebuah keberuntungan dan sebaliknya jika engkau lalai akan membunuhmu. <br><br>-- Ibadah Online --</a>";
kata_bijak[31]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Teruslah optimis dan berpikir positif dalam hidupmu. <br><br>-- Ibadah Online --</a>";
kata_bijak[32]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Ketika ada sebuah keinginan yang muncul untuk memulai suatu hal yang sudah di targetkan, maka harus muncul sebuah keberanian untuk menyelesaikannya. <br><br>-- Ibadah Online --</a>";
kata_bijak[33]="<a href='https://aksesglobalmultimedia.com/pulsa.html'>Jangan menunda untuk lekas berusaha demi keindahan masa depanmu <br><br>-- Ibadah Online --</a>";

var acak=Math.floor(33*Math.random());
document.write("<i>");
document.write(kata_bijak[acak]);
document.write("</i>");
